name: Build Nukkit Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Nukkit
        run: |
          curl -L -o nukkit.jar https://repo.opencollab.dev/maven-snapshots/cn/nukkit/nukkit/1.0-SNAPSHOT/nukkit-1.0-20251001.065813-1220.jar

      - name: Compile plugin
        run: |
          mkdir -p out
          javac -cp nukkit.jar -d out $(find src -name "*.java")

      - name: Package JAR
        run: |
          mkdir -p build
          jar cf build/GravityPush.jar -C out/ . plugin.yml

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: GravityPush
          path: build/GravityPush.jar
